export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = 'LOGOUT'

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const FAVOURITE_REQUEST = "FAVOURITE_REQUEST"
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS"
export const FAVOURITE_FAILURE = "FAVOURITE_FAILURE"

export const USER_INFO_REQUEST = "USER_INFO_REQUEST"
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS"
export const USER_INFO_FAILURE = "USER_INFO_FAILURE"

